### ISSUE TITLE
Automatic linking for iOS fails

### ISSUE THREAD

**Issue by ma-pe** [maicki/react-native-event-bridge#23] opened 2018-01-15 12:13 UTC
I receive an `Maximum call stack size exceeded`-Error when trying to automatically link this library to ios (`react-native link react-native-event-bridge`).

Linking for Android doesn't fail.

**Comment by maicki** [comment] 2018-01-20 17:56
@ma-pe What RN version did you use. I just tried it out with the RN version and it worked as expected.

**Comment by maicki** [comment] 2018-01-22 17:03
@ma-pe Could you try it out again on your side and maybe provide a bit more information. As said previously, unfortunately I couldn't reproduce it yet.

**Comment by ma-pe** [comment] 2018-01-22 21:27
@maicki I am using react-native 0.51.0.

I already manually linked this plugin. When I run `react-native link react-native-event-bridge` now, it says that both platforms have already been linked.

**Comment by maicki** [comment] 2018-01-23 16:57
I tried it again with a bootstrapped project via `react-native` as well as an ejected app via `create-react-native-app`, in both cases it worked fine.

I will close this issue for now as I think it's more a problem of the react native package management as react-native-event-bridge.

**Closed by maicki** 2018-01-23 16:57 UTC
